# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfc4b48f950cba780b46df0a7323221f69c82eb9201e9b92e24f6b5033b244f1ed170a017715b1de5d498d2ffa7e509caf00ae4b67f443732bf6c1f8df7b39fd

test:
  secret_key_base: ccef6df52bf8943be8492ca234d65eb1f495821b99336fa3331b9579a35c88b1ec788aff8d943aa498542ec3705e4146abfa2b36b6bf314bce675e6a7454b65e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
